# golangci-lint configuration for using lingo as a custom plugin.
#
# Prerequisites:
#   1. Build the plugin .so:
#      go build -buildmode=plugin -o lingo.so ./plugin/
#   2. Run golangci-lint:
#      golangci-lint run ./...
#
# Note: Go plugin system works on Linux/macOS only (not Windows).

version: "2"

linters:
  enable:
    - lingo

linters-settings:
  custom:
    lingo:
      # type: goplugin — load from a compiled .so file.
      type: goplugin
      # Path to the compiled plugin binary.
      path: ./lingo.so
      description: "Linter for log messages: lowercase start, English only, no emoji, no sensitive data"
      original-url: https://github.com/PriestFaria/lingo
      # Inline configuration (recommended — no separate .lingo.json needed).
      # All keys are optional; absent filters default to enabled.
      settings:
        filters:
          first_letter: true
          english: true
          emoji: true
          security: true
        security:
          extra_keywords:
            - cvv
            - ssn
            - otp

      # Alternatively, point to an external .lingo.json file:
      # settings:
      #   config: .lingo.json
